#file: noinspection YAMLSchemaValidation
name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Adding the Private key to a Github Actions Workflow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      # Adding a correct known_hosts value
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts

      - name: Update Repo & Re-Run Service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Set variables
            git config --global user.email "ozik.dev@gmail.com"
            git config --global user.name "Ozz"
            
            BRANCH_NAME="main"
            SERVICE_NAME="bot_assistant"
            
            cd /root/chatgpt-telegram-bot
            
            # Fetch the latest changes
            git fetch origin $BRANCH_NAME
            
            # Reset the local branch to match the remote
            git reset --hard origin/$BRANCH_NAME
            
            # Pull the latest changes
            git pull origin $BRANCH_NAME
            
            /root/chatgpt-telegram-bot/venv/bin/pip3 install -r ./requirements.txt
            
            # Restart the service 
            sudo systemctl restart $SERVICE_NAME
            
            # Check the service status
            sudo systemctl status $SERVICE_NAME